
#Redis配置
spring:
  redis:
    host: localhost
    port: 6379
    database: 2
    timeout: 100ms
    jedis:
      pool:
        max-active: 8

#Mybatis配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: bkq19900823
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true


  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**

mybatis:
  mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: main.bkqStudy.entity
server:
  port: 8081
